import fetch from "node-fetch";

const HF_API_TOKEN = process.env.HF_API_TOKEN;


const HF_MODEL_ID =
  process.env.HF_MODEL_ID || "meta-llama/Llama-3.2-1B-Instruct";

/**
 * Blog yazısı için prompt oluştur
 */
function buildPrompt(topic) {
  return `
You are an expert technical blog writer.

Write a high-quality technical blog article in English about: "${topic}".

FORMAT:
- First line: only the article title (no prefix like "Title:")
- Then one blank line
- Then 3 to 6 short paragraphs as the article body.

Do NOT add anything else before or after the article.
`.trim();
}

/**
 * HF çıktısını title + content olarak parçala
 */
function parseArticleText(rawText) {
  const text = (rawText || "").trim();
  if (!text) {
    return {
      title: "Untitled Article",
      content: "No content generated by the AI.",
    };
  }

  const lines = text.split("\n");

  const firstLine = lines[0] || "Untitled Article";
  const title = firstLine.replace(/^["'#*\s]+/, "").trim();

  // 2. satır (boş satır) sonrasını gövde olarak al
  const body = lines.slice(2).join("\n").trim() || text;

  return { title, content: body };
}

/**
 * HuggingFace Router API üzerinden makale üret
 */
export async function generateArticle(topic = "Modern web development and DevOps best practices") {
  if (!HF_API_TOKEN) {
    throw new Error("HF_API_TOKEN is not configured");
  }

  const prompt = buildPrompt(topic);

  const response = await fetch(
    "https://router.huggingface.co/v1/chat/completions",
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${HF_API_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: HF_MODEL_ID,
        messages: [
          {
            role: "system",
            content: "You are an expert technical blog writer.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
        max_tokens: 800,
        temperature: 0.7,
      }),
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    console.error("❌ HuggingFace API error:", response.status, errorText);
    throw new Error(`HuggingFace API error: ${response.status}`);
  }

  const data = await response.json();

  const generatedText =
    data?.choices?.[0]?.message?.content ||
    "";

  if (!generatedText) {
    console.warn("⚠️ Unexpected HF response format:", JSON.stringify(data));
  }

  const article = parseArticleText(generatedText);

  return {
    title: article.title,
    content: article.content,
  };
}